function [freqnorm]=Histo_setted_rep(data,mycolor,bins,mymax,myxlabel,mytitle,mymode,myhold,myind)
%CREATEFIGURE(data,YVECTOR1)
%  data:  bar xvector
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 13-May-2013 15:31:08

if nargin < 5
   %bins=(min(data):(max(data)-min(data))/20:max(data)); 
   mytitle = '';
   myxlabel='Displacement [nm]'
   mymode='p';
   myhold='y';
   myind=[];
   
end

if nargin < 6
   %bins=(min(data):(max(data)-min(data))/20:max(data)); 
   mytitle = '';
   
   mymode='p';
   myhold='y';
   myind=[];
   
end


if myhold(1)=='n'
% Create figure
    figure1 = figure;
    axes1 = axes('Parent',figure1,'FontSize',30);
    box(axes1,'on');
    hold(axes1,'all');
    
elseif myhold(1)=='y'

    hold on
    axes1=gca;
    box(axes1,'on');
end
% Create axes


% Create bar
[freq,bincenters]=hist(data,bins,'Parent',axes1,'DisplayName','800ms exposure, 30mW');

if mymode(1)=='h'
    
    hist(data,bins,'Parent',axes1,'DisplayName','800ms exposure, 30mW');
    title(mytitle);
    % Create xlabel
    xlabel(myxlabel,'FontSize',30);
    xlim([0, max(bins)-max(bins)*0.05]);

    % Create ylabel
    ylabel({'Frequency'},'FontSize',30);
    ylim([0, max(freq)+max(freq)*0.1]);
    % Create legend
    M=fix(mean(data));
    V=fix(var(data));
    ttt=text(2/4*max(bins),3/4*max(freq),strcat('Mean =',sprintf(' %0.4g',M)));
    ttt2=text(2/4*max(bins),2.5/4*max(freq),strcat('\sigma =',sprintf(' %0.4g',fix(sqrt(V)))));
    set(ttt,'FontSize', 30);
    set(ttt2,'FontSize', 30);
    set(axis1,'FontSize', 30);


end

if mymode(1)=='p'
    
    freq=freq(1:end-1);
    norm=sum(freq);
    step=diff(bins(end-1:end));
    freqnorm=freq/double(norm)/step;
    plot(bins(1:end-1)+step/2,freqnorm,'-', 'color',mycolor,'linewidth',3,'markersize',35,'Parent',axes1,'DisplayName',mytitle);
    
    % Create xlabel
    xlabel(myxlabel,'FontSize',30);
    xlim([0, max(bins)-max(bins)*0.05]);

    % Create ylabel
    ylabel({'PDF'},'FontSize',30);
    %ylim([0, nanmax(freqnorm)+nanmax(freqnorm)*0.1]);
    % Create legend
    M=nanmean(data(data<bins(end-1)));
    V=nanvar(data(data<bins(end-1)));
    sigma=sqrt(V);
    if M>1
        M=fix(nanmean(data(data<bins(end-1))));
        V=fix(nanvar(data(data<bins(end-1))));
        sigma=fix(sqrt(V));
    end

    N=length(data(data<bins(end-1)));

    mystring=strcat(num2str(myind),'Mean=',sprintf(' %0.4g',M),...
        num2str(myind),' \sigma=',sprintf(' %0.5g',sigma),...
            num2str(myind),' N=',sprintf(' %0.5g',fix((N))));
    ttt=text(1/6*max(bins),3/6*max(mymax),mystring,'color',mycolor);
    %ttt2=text(3/6*max(bins),3/6*max(mymax),strcat(,'color',mycolor);
    %ttt3=text(4/6*max(bins),3/6*max(mymax),strcat(num2str(myind),'N =',sprintf(' %0.4g',fix((N)))),'color',mycolor);
    set(ttt,'FontSize', 15);
    %set(ttt2,'FontSize', 20);
    %set(ttt3,'FontSize', 20);
    set(gca,'FontSize', 20);

    title(mytitle, 'FontSize', 20);
    
end

